#!/bin/sh

bspc rule -r "*"
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Aesthetics
bspc config border_width 3
bspc config borderless_monocle true
bspc config focused_border_color "#FF0000"
bspc config gapless_monocle true
bspc config automatic_scheme alternate

# Rules
bspc rule -a "Tor Browser" desktop='^9' follow=on state=pseudo_tiled
bspc rule -a "firefox:Toolkit" state=floating sticky=on
bspc rule -a "Zathura" state=tiled

# Launch programs
wallpaper
lemonpanel &
