#!/bin/sh

bspc rule -r "*"

# Setup monitors
#mainmonitor="$(xrandr | awk '/^[A-Z]/ && !/Screen|VIRTUAL|LVDS|disconnected/ {print $1}')" # Look for other monitors than the laptop screen
#if [ -n "$mainmonitor" ]; then
#	xrandr --output "$mainmonitor" --auto --output "$(xrandr | awk '/LVDS/ {print $1}')" --off # Output to the external monitor and turn off the latop display
#	bspc monitor "$mainmonitor" -d 1 2 3 4 5 6 7 8 9 10
#else
#	bspc monitor -d 1 2 3 4 5 6 7 8 9 10
#fi
#bspc desktop -f 1

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Aesthetics
bspc config border_width 3
bspc config borderless_monocle true
bspc config focused_border_color "#FF0000"
bspc config gapless_monocle true
bspc config automatic_scheme alternate

# Rules
bspc rule -a "Tor Browser" desktop='^9' follow=on state=pseudo_tiled
bspc rule -a "firefox:Toolkit" state=floating sticky=on
bspc rule -a "Zathura" state=tiled

# Launch programs
xwallpaper --zoom "$(find "$HOME/.local/share/wallpaper" -type f | shuf -n 1)"
lemonpanel &
