" Change font type and font size in gvim
set guifont=Consolas:h14

" Spellcheck
map <F6> :setlocal spell! spelllang=en_us<CR>

" Relative line numbering
set number relativenumber

" Better tab completion
set wildmenu

" Open splits at the bottom and right
set splitbelow splitright

" Disable text wrapping
set wrap lbr

" Syntax highlighting
syntax on

" Highlight all search matches
set hlsearch

" Change colorscheme to solarized
colorscheme solarized8

" Turn on backspace when in insert mode
set backspace=indent,eol,start

" Show line and character nummber
set ruler

" Search case insensitivly
set ignorecase

" Math in markdown (use pandoc to compile into docx)
autocmd Filetype markdown inoremap ;1 <Esc>?#<cr>yy<c-o>p$ciw<c-r>=<c-r>"+1<cr><cr>$<++>$<cr><cr><++><Esc>?\$<++>\$<cr>lca<
autocmd Filetype markdown inoremap ;2 <Esc>?#<cr>yy<c-o>p$ciw<c-r>=<c-r>"+1<cr><cr> a) <cr> b) $<++>$<cr> c) $<++>$<cr><cr><++><Esc>?a)<cr>$A$$<Esc>i
autocmd Filetype markdown inoremap <tab><tab> <Esc>/<++><cr>"_c4l

