#! /bin/sh

sxhkd &
bspc rule -r "*"

mainmonitor="$(bspc query --monitors --names | grep -v LVDS | head -n 1)"

if [ "$mainmonitor" != "LVDS*" ]; then
	xrandr --output "$mainmonitor" --auto --output LVDS1 --off
fi
bspc monitor $mainmonitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# coloring
bspc config normal_border_color  "#eee8d5"
bspc config focused_border_color "#dc322f"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Pick a random picture from the given folder and set as wallpaper
feh --bg-fill --no-fehbg $(ls ~/.config/wallpaper/*.jpg | shuf -n 1)

xsetroot -cursor_name left_ptr
# Start the panel script
~/.config/panel/panel.sh | lemonbar -g x24 -f "-*-fixed-*-*-*-*-10-*-*-*-*-*-*-*" -B#073642 -F#eee8d5
