export ZDOTDIR=$HOME/.config/zsh
export GIT_EDITOR=vim
export PATH=$PATH:$HOME/.local/bin
export XINITRC=$HOME/.config/X11/xinitrc
export XAUTHORITY=$HOME/.config/X11/Xauthority
export LESSHISTFILE=-

if [[ "$(tty)" = "/dev/tty1" ]]; then
	startx "$HOME/.config/X11/xinitrc" &
fi
