#!/bin/sh

[ -z "$1" ] && { echo "No device specified"; exit 1 ;}

mkdir /boot/syslinux
#cp /usr/lib/syslinux/bios/*.c32 /boot/syslinux/
extlinux --install /boot/syslinux
dd if=/usr/lib/syslinux/bios/mbr.bin of="$1" bs=440 count=1 conv=notrunc
vi /boot/syslinux/syslinux.cfg
