#!/bin/sh

[ -z "$1" ] && { echo "No device specified"; exit 1 ;}

bootctl install
mkdir -p /boot/loader/entries

echo \
"default arch
timeout 5" > /boot/loader/loader.conf

echo \
"title Archlinux
linux /vmlinuz-linux
initrd /initramfs-linux.img
options root=UUID=$(blkid -o value -s UUID "$1") rw" > /boot/loader/entries/arch.conf

bootctl list
