#!/bin/sh

for dev do
	bootctl install
	mkdir -p /boot/loader/entries
	cat > /boot/loader/loader.conf <<-EOF
		default arch
		timeout 5
	EOF
	cat > /boot/loader/entries/arch.conf <<-EOF
		title Archlinux
		linux /vmlinuz-linux
		initrd /initramfs-linux.img
		options root=UUID=$(blkid -o value -s UUID "$dev") rw
	EOF
	bootctl list
done
